name: deploy-to-gh-pages

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '3 6 * * *'
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update Polyhedra gh-pages
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          SOURCE_BRANCH="master"
          TARGET_BRANCH="gh-pages"
          REPO=`git config remote.origin.url`
          SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
          SHA=`git rev-parse --verify HEAD`
          echo "Running ~The Build~"
          git clone $REPO out
          cd out
          git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
          cd ..
          rm -rf out/build/* || exit 0
          mkdir -p out/data
          mkdir -p out/static
          python app.py no_file_cache
          cp .gitignore out/.gitignore
          cp README.md out/README.md
          cd out/build
          cp -r * ..
          cd ..
          if [[ -z `git diff --exit-code` ]]; then echo "No changes to pages on this push; exiting."; exit 0; fi
          git config user.name "DuskDragon-gh-pages-Action"
          git config user.email "duskdragon@gmail.com"
          git add -A
          git commit -m "Deploy to GitHub Pages: ${SHA}"
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
          git push $SSH_REPO $TARGET_BRANCH
